require 'open-uri'
require 'nokogiri'
require 'sgf'
require 'mechanize'

require_relative 'gotasku/gotasku'
require_relative 'gotasku/problem'
require_relative 'gotasku/difficulty_string'
require_relative 'gotasku/rating_string.rb'
require_relative 'gotasku/parser'
require_relative 'gotasku/user'
require_relative 'gotasku/session'
