require 'open-uri'
require 'nokogiri'
require 'sgf'
require 'mechanize'
require 'mongo'

require_relative 'gotasku/gotasku'

require_relative 'gotasku/exceptions'
require_relative 'gotasku/problem'
require_relative 'gotasku/document'
require_relative 'gotasku/difficulty_string'
require_relative 'gotasku/rating_string'
require_relative 'gotasku/display'
require_relative 'gotasku/parser'
require_relative 'gotasku/user'
require_relative 'gotasku/session'
require_relative 'gotasku/query'
